# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: "vi_spacy_model"
  - name: SpacyTokenizer
  # Creates a vector representation of user message and response (if specified) using the spaCy featurizer.
  - name: SpacyFeaturizer
  # support regex
  - name: RegexFeaturizer
  # support entity extraction.
  - name: LexicalSyntacticFeaturizer
  # Creates bag-of-words representation of user messages, intents, and responses.
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
    # entities, intent and intent_ranking
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: DucklingEntityExtractor
    url: "http://localhost:8000"
    dimensions: ["time"]
    locale: "vi_VN"
    timezone: "Asia/Ho_Chi_Minh"
    timeout: 5
    # predicted response templates, confidence and the response key under the retrieval intent
  - name: ResponseSelector
    epochs: 100
    # lassifies a message with the intent nlu_fallback if the NLU intent classification scores are ambiguous. The confidence is set to 1 - top intent confidence.
  - name: FallbackClassifier
    threshold: 0.7

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
